project:
  type: website
  output-dir: docs
 
website:
  title: "Hyunsoo Kim"
  
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  navbar:
    left:
      - index.qmd
      - Data_Mining.qmd
      - R_Basic.qmd
      - Data_Visualization.qmd
      - Regression_Analysis.qmd
      - Spatial_Information_Analysis.qmd
      - OpenData_Analysis.qmd
      - BigData_Analysis.qmd

    right:
      - icon: github
        href: https://github.com/hyunsookim0813


  sidebar:
    style: 'docked'
    search: true
    contents: 
      - section: 'Profile'
        contents: 
        - index.qmd
      
      - section: 'Study'
        contents:
        - Data_Mining.qmd
        - R_Basic.qmd
        - Data_Visualization.qmd
        - Regression_Analysis.qmd
        - Spatial_Information_Analysis.qmd
        - OpenData_Analysis.qmd
        - BigData_Analysis.qmd

    page-footer: 
      left: 'Made by Quarto'



format:
  html:
    #theme: minty
    theme:
        light: [cosmo, theme.scss, anari-custom.scss]
        dark: [cosmo, theme-dark.scss, anari-custom.scss]
    toc: true
    self-contained: true
    smooth-scroll: true
    # code-fold: true
    code-tools: true
    # toc-depth : 5
    # number-sections: true
    css: styles.css
      
editor: visual

